[package]
name = "ifood_logistica"
version = "0.1.0"
edition = "2021"

[dependecies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.6", features = ["postgres", "runtime-tokio-rustls"] }
uuid = "1"
chrono = "0.4"

[dependencies]
actix-web = "4.10.2"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sqlx = "0.8.5"
tokio = { version = "1.44.2", features = ["full"] }
