version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - name=value
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      - name=value
      - 
      - 
    ports:
      -
    volumes:
      -

volumes:
  postgres_data: